### ISSUE TITLE
Is @ToJans a fictitious alter ego of Damian Hickey?

### ISSUE THREAD

**Issue by mathiasverraes** [ToJans/AMA#5]
I mean, it all works out if you think about it...

**Comment by ToJans** [comment]
How did you figure it out? Because we were never at the same place & time at @buildstufflt ?

Anyway, you did figure it out, so if you want further information, please start reading [here](http://en.wikipedia.org/wiki/Dissociative_identity_disorder).

This is a very severe case of DID; my alter ego even has a different native tongue and starts chanting songs about a certain person named Molly Mallone when he gets homesick... 

As you obviously have put in the extra effort, I'll reward you with a pic that exposes everything...

![the_truth](https://cloud.githubusercontent.com/assets/155977/5317183/c3183034-7c94-11e4-8fd0-0bc20f79088d.gif)

**Comment by damianh** [comment]
https://www.youtube.com/watch?v=vdxLxnhGnvo

Alive alive Ohhh! Alive alive Ohhh!

**Comment by ToJans** [comment]
:clap: Alive alive Ohhh! :clap:  Alive alive Ohhh! :notes:

**Comment by damianh** [comment]
Tried to set that gif as my twitter profile pic, didn't work :(

**Comment by ToJans** [comment]
LOL, we might as well admit that we are the same person now, don't we!

**Comment by ToJans** [comment]
@mathiasverraes if this is a satisfying answer, feel free to close the issue ;)

**Comment by mathiasverraes** [comment]
Can't. Stop. Staring. 
Dat wiggly nose!

**Comment by ToJans** [comment]
:laughing:

**Comment by ONE75** [comment]
Awesome! :)

**Comment by ToJans** [comment]
I assume this one can be considered as answered? Closing it....

**Comment by mathiasverraes** [comment]
Yes, this topic can be closed. Yes, all questions have been answered. The all the facts are on the table. The story was fully exposed to the general public. The truth is fully uncovered. There is nothing more to say about this. Nothing to see here, move along. There is nothing suspicious about any of this, no need for concern. Looking for hidden information or a secret agenda is futile, as there is none. Nobody has anything to hide. There is no reason to suspect otherwise. No, I have not been bribed by Damian to write this message.
